# Generated by Django 4.1.1 on 2022-10-15 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date of delete'),
        ),
        migrations.AddField(
            model_name='basket',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AddField(
            model_name='basket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date of create'),
        ),
    ]
