# Generated by Django 4.1.1 on 2022-10-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_order_remove_basket_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date of delete'),
        ),
        migrations.AddField(
            model_name='basket',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
    ]
