# Generated by Django 4.1.1 on 2022-10-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_basket_deleted_at_remove_basket_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Count'),
        ),
    ]
